server:
  port: 8081
spring:
  application:
    name: Fokuz
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/fokuz
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
