server:
  port: 8081
spring:
  application:
    name: Fokuz
  datasource:
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
